vtape-cp-sum-and-xz: Add logging, display ISO 8601 times.

diff --git a/Scripts/vtape-cp-sum-and-xz b/Scripts/vtape-cp-sum-and-xz
--- a/Scripts/vtape-cp-sum-and-xz
+++ b/Scripts/vtape-cp-sum-and-xz
@@ -11,34 +11,39 @@ function die () {
 HOSTNAME="$(hostname)"
 DESTDIR="/run/media/tkb/Utgard/From-NAS"
 
-find /media/tkb/vaxtapes -name \*.vtape | sort | while read FN
-do
-    ((FILENUM++))
-    echo "==========> Working on file #$FILENUM, $FN"
-    DIRNAME="$(dirname $FN)"
-    BASENAME="$(basename $FN)"
-    DESTNAME="$DESTDIR/$BASNAME"
-    COMPNAME="$BASENAME.xz"
+{
+    echo "==========> Starting copy, sum, and compress  at $(date -Iseconds)"
 
-#    echo "DIRNAME=$DIRNAME
-#BASENAME=$BASENAME
-#DESTNAME=$DESTNAME
-#COMPNAME=$COMPNAME"
-    
-    [[ -e $DESTDIR/$COMPNAME ]] && {
-        echo "DESTDIR/$BN.xz already exists, skipping $FN"
-        continue
-    }
-    echo "==========> Copying $FN to $DESTDIR"
-    time cp -v $FN $DESTDIR/ || die 1 "Error copying $FN to $DESTDIR, exiting."
-    (
-        cd $DESTDIR
-        echo "==========> sha512sum $BASENAME"
-        time sha512sum --binary $BASENAME >$BASENAME.sha512sum.$HOSTNAME ||
-            die 1 "Error sha512summing $BASENAME, exiting."
-        echo "==========> xz --compress $BASENAME"
-        time xz --compress $BASENAME ||
-            die "Error xz --compressing $BASENAME, exiting."
-    )
-    scream
-done
+    find /media/tkb/vaxtapes -name \*.vtape | sort | while read FN
+    do
+        ((FILENUM++))
+        echo "==========> Working on file #$FILENUM, $FN at $(date -Iseconds)"
+        DIRNAME="$(dirname $FN)"
+        BASENAME="$(basename $FN)"
+        DESTNAME="$DESTDIR/$BASNAME"
+        COMPNAME="$BASENAME.xz"
+
+        #    echo "DIRNAME=$DIRNAME
+        #BASENAME=$BASENAME
+        #DESTNAME=$DESTNAME
+        #COMPNAME=$COMPNAME"
+        
+        [[ -e $DESTDIR/$COMPNAME ]] && {
+            echo "DESTDIR/$BN.xz already exists, skipping $FN"
+            continue
+        }
+        echo "==========> Copying $FN to $DESTDIR"
+        time cp -v $FN $DESTDIR/ || die 1 "Error copying $FN to $DESTDIR, exiting  at $(date -Iseconds)."
+        (
+            cd $DESTDIR
+            echo "==========> sha512sum $BASENAME  at $(date -Iseconds)"
+            time sha512sum --binary $BASENAME >$BASENAME.sha512sum.$HOSTNAME ||
+                die 1 "Error sha512summing $BASENAME, exiting."
+            echo "==========> xz --compress $BASENAME at $(date -Iseconds)"
+            time xz --compress $BASENAME ||
+                die "Error xz --compressing $BASENAME, exiting  at $(date -Iseconds)."
+        )
+        scream
+    done
+    echo "==========> Finished copy, sum, and compress  at $(date -Iseconds)"
+} | log ~/tmp/vtape-cp-sum-and-xz
